"""Init database tables

Revision ID: cb98e6eaedd4
Revises: 
Create Date: 2024-08-22 13:40:24.190127

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb98e6eaedd4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("""CREATE EXTENSION IF NOT EXISTS "uuid-ossp";"""))

    op.create_table(
        "bet",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("bet_amount", sa.Numeric(), nullable=False),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bet")
    # ### end Alembic commands ###
